[package]
name = "gallide-bin"
version = "0.1.7"
edition = "2024"
readme = "crateREADME.md"
description = "The binary for gallide, this is meant to be called by an external bash script"
homepage = "https://github.com/Djalcoding/Gallide"
repository = "https://github.com/Djalcoding/Gallide"
license-file = "LICENSE.txt"

[dependencies]
crossterm = "0.29.0"
djal_parser = "0.2.0"
ratatui = "0.30.2"
