[package]
name = "gallide-bin"
version = "0.1.1"
edition = "2024"
readme = "crateREADME.md"
description = "The binary for gallide, this is meant to be called by an external bash script"
homepage = "https://github.com/Djalcoding/Gallide"
repository = "https://github.com/Djalcoding/Gallide"
license-file = "LICENSE.txt"

[dependencies]
djal_parser = "0.2.0"
termion = "4.0.5"
tui = { version = "0.19", default-features = false, features = ['termion'] }
