!! Main Box
  text color: white 
  border color: white
  background color: black 
!! [Plain, Thick, Double, Rounded, None] 
  border type: Plain

!! Focus (Underline entries)
  focus color: white 
  focus text color: black
  focus text: "> " 

!! Directories
  main title: " Directories "
  directory symbol: "" 
  directory symbol color: white 

!! Files
  file symbol : ""
  file symbol color: white 

!! Search bar
  searchbar border color: white 
  searchbar text color: white 
  insert searchbar color: red 
  case sensitive: no
  searchbar title: " Search "
  searchbar background color: black 
!! [Plain, Thick, Double, Rounded, None]
  searchbar border type: Plain

!! Tool Tips
  tooltip text color: black 
  tooltip keybind color: white
  tooltip highlight color: white 

display directory: yes
enable searchbar: yes
display tooltips: yes

